// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ugvgexvxkwbyxjpcwbdb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVndmdleHZ4a3dieXhqcGN3YmRiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1MTc3MzUsImV4cCI6MjA2NDA5MzczNX0.kKbf195QEiPEx1_GLKLXZy_Pk7p8t-RIsHvtQOnEaf8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);